git clone https://github.com/buschmais/jqa-commandline-tool
git clone https://github.com/buschmais/jqa-maven-plugin
git clone https://github.com/buschmais/jqa-core-framework
git clone https://github.com/buschmais/jqa-neo4j-backend
git clone https://github.com/buschmais/jqa-cdi-plugin
git clone https://github.com/buschmais/jqa-ejb3-plugin
git clone https://github.com/buschmais/jqa-graphml-plugin
git clone https://github.com/buschmais/jqa-java-plugin
git clone https://github.com/buschmais/jqa-java8-plugin
git clone https://github.com/buschmais/jqa-javaee6-plugin
git clone https://github.com/buschmais/jqa-jaxrs-plugin
git clone https://github.com/buschmais/jqa-jpa2-plugin
git clone https://github.com/buschmais/jqa-json-plugin
git clone https://github.com/buschmais/jqa-junit-plugin
git clone https://github.com/buschmais/jqa-m2repo-plugin
git clone https://github.com/buschmais/jqa-maven3-plugin
git clone https://github.com/buschmais/jqa-osgi-plugin
git clone https://github.com/buschmais/jqa-rdbms-plugin
git clone https://github.com/buschmais/jqa-spring-plugin
git clone https://github.com/buschmais/jqa-testng-plugin
git clone https://github.com/buschmais/jqa-tycho-plugin
git clone https://github.com/buschmais/jqa-xml-plugin
git clone https://github.com/buschmais/jqa-yaml-plugin

git clone https://github.com/softvis-research/jqa-javasrc-plugin
git clone https://github.com/softvis-research/jqa-c-plugin
git clone https://github.com/softvis-research/jqa-plsql-plugin
git clone https://github.com/softvis-research/jqa-githubissues-plugin
git clone https://github.com/softvis-research/jqa-kieker-plugin
git clone https://github.com/softvis-research/jqa-dashboard
git clone https://github.com/softvis-research/jqa-jira-plugin
git clone https://github.com/softvis-research/jqa-javascript-plugin
git clone https://github.com/softvis-research/jqa-php-plugin

git clone https://github.com/antlr/antlr4
hg clone https://bitbucket.org/jython/jython
