package com.kev007.jqa.plugin.python.api.model;

import com.buschmais.jqassistant.plugin.common.api.model.FileDescriptor;
import com.buschmais.xo.api.annotation.Abstract;
import com.buschmais.xo.neo4j.api.annotation.Label;

/**
 * Defines label "Python" which is applied to all nodes generated by this plugin.
 */
@Abstract
@Label("Python")
public interface PythonFileDescriptor extends PythonDescriptor, FileDescriptor {


}
